import type { Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <nav className="flex items-center justify-between p-4 border-b border-gray-200">
            <div className="flex items-center gap-6">
              <Link href="/" className="text-xl font-semibold">
                MyApp
              </Link>
              <SignedIn>
                <div className="hidden md:flex items-center gap-4">
                  <Link href="/dashboard" className="hover:text-blue-600 transition-colors">
                    Dashboard
                  </Link>
                  <Link href="/admin" className="hover:text-blue-600 transition-colors">
                    Admin
                  </Link> 
                  <Link href="/editor" className="hover:text-blue-600 transition-colors">
                    Editor
                  </Link> 
                  <Link href="/task" className="hover:text-blue-600 transition-colors">
                    Task
                  </Link>            
                </div>
              </SignedIn>
            </div>
            
            <div className="flex items-center gap-4">
              <SignedOut>
                <SignInButton mode="modal">
                  <button className="px-4 py-2 rounded-md hover:bg-gray-100 transition-colors">
                    Sign in
                  </button>
                </SignInButton>
                <SignUpButton mode="modal">
                  <button className="px-4 py-2 bg-black text-white rounded-md hover:bg-gray-800 transition-colors">
                    Sign up
                  </button>
                </SignUpButton>
              </SignedOut>
              <SignedIn>
                <UserButton afterSignOutUrl="/" />
              </SignedIn>
            </div>
          </nav>
          
          <main className="p-4">
            {children}
          </main>
        </body>
      </html>
    </ClerkProvider>
  )
}